# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 个人信息
title: eziochiu's Blog
subtitle: 一个会逆向的iOS工程师
# description: 成功不是将来才有的<br>而是决定去做的那一刻起<br>持续累积而成
author: eziochiu
email: eziochiuchina@hotmail.com
keywords: "Objective-C、Swift、Cocos2d-js、HTML5、React Native、JavaScript、PHP、Python、Java"
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://eziochiu.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# 文件夹
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  README.md

# 头像设置
avatar: /images/head.png

# 社交链接
# social:
#   GitHub: https://github.com/eziochiu
#   Twitter: https://twitter.com/wangwanjie
#   微博: http://www.weibo.com/2406245873/profile?topnav=1&wvr=6
#   Facebook: https://www.facebook.com/wangwanjie123
#   QQ: http://wpa.qq.com/msgrd?v=3&uin=396736694&site=qq&menu=yes

# 社交链接 icon
# social_icons:
#   enable: true
#   # Icon Mappings.
#   # KeyMapsToSocialItemKey: NameOfTheIconFromFontAwesome
#   GitHub: github
#   Twitter: twitter
#   微博: weibo
#   Facebook: facebook
#   QQ: qq

# 友情链接
# links_title: 友情链接
# links:
#   泊学网: https://boxueio.com
#   锤子科技: http://www.smartisan.com/
#   ObjC中国: https://objccn.io/
#   Swift evolution: https://github.com/apple/swift-evolution

# 字体
font:
  enable: true

  # 外链字体库地址，例如 //fonts.googleapis.com (默认值)
  host:

  # 全局字体，应用在 body 元素上
  global:
    external: true
    family: Monda

  # 标题字体 (h1, h2, h3, h4, h5, h6)
  headings:
    external: true
    family: Roboto Slab

  # 文章字体
  posts:
    external: true
    family:

  # Logo 字体
  logo:
    external: true
    family: Lobster Two
    size: 24

  # 代码字体，应用于 code 以及代码块
  codes:
    external: true
    family: PT Mono

# 写作
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# 默认高亮
# 主题
theme: NexT2

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config
## highlight in frontend, the plugin (backend) just do some prepare work.
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start
hljs:
  enable: false #true to enable the plugin
  line_number: frontend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: 代码
    right: ':'
    copy: 拷贝

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# 日期、时间格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页
## Set per_page to 0 to disable pagination
# per_page: 8
pagination_dir: page
# 设置页面文章的篇数
index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# algolia:
#   applicationID: 'TZKAYD1IX3'
#   apiKey: '0948641672f6c1751c491b30047ab041'
#   adminApiKey: '987381715b0590a1fc9e848343aeb4d0'
#   indexName: 'ForHexo'
#   chunkSize: 5000

# 本地搜索
# search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000

# 部署到github
deploy:
  type: git
  repository: https://github.com/eziochiu/eziochiu.github.io.git
  branch: master

# leancloud_counter_security:
#   enable_sync: false
#   app_id: ftmd6Qz8JIuEqadbKNDX62Sv-gzGzoHsz
#   app_key: Bf55iVdUR8NPPHlSxEt30XbD
#   username: <<your username>> # Will be asked while deploying if is left blank
#   password: <<your password>> # Recommmended to be left blank. Will be asked while deploying if is left blank

feed:
    type: atom
    path: atom.xml
    limit: 20
    hub:
    content:
    content_limit:
    content_limit_delim: ' '

# https://github.com/xiazeyu/live2d-widget-models
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: true
  log: false
  model:
    use: live2d-widget-model-wanko
  display:
    superSample: 2
    width: 150
    height: 300
    position: right
    hOffset: -30
    vOffset: -180
  mobile:
    show: false
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

# 字数统计
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true